// frontend/src/App.jsx
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import { Home, Booking, Structure, HTMLErrorCodes, Register } from './containers';
import { Header, Footer } from './components';
const App = () => {
  return (
    <>
      <Header />
      <Routes>
        <Route exact path="/" element={<Home />} />
        <Route path="/structure" element={<Structure />} />
        <Route path="/booking" element={<Booking />} />
        <Route path="/register" element={<Register />} />
        <Route path="*" element={<HTMLErrorCodes status={404} />} />
      </Routes>
      <Footer />
    </>
  );
};

export default App;

// svelte/src/App.svelte
<script>
  import Router from "svelte-spa-router";

  //Components
  import { Header, Footer } from "./components";

  //Pages
  import { Home, PageNotFound, Login, Register, Dashboard } from "./pages";

  const routes = {
    "/": Home,
    "/login": Login,
    "/register": Register,
    "/dashboard": Dashboard,
    "*": PageNotFound,
  };
</script>

<Header />
<main>
  <Router {routes} />
</main>
<Footer />
